[package]
name = "rust-pokemon-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.27", features = ["derive"] }
color-eyre = "0.6.3"
eyre = "0.6.12"
futures = "0.3.31"
rand = "0.8.5"
rustemon = "4.0.0" 
tokio = { version = "1", features = ["full"] }
